name: SlimeLib
version: ${project.version}

author: Phoenix
website: https://github.com/PhoenixCodingStuff/SlimeLib
description: A Minecraft Development Library for SlimeCraftSMP plugins.

main: me.phoenix.slimelib.SlimeLib
api-version: 1.20
depend: [Slimefun]
